name: Blue Cross Cat Tracker

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  track-bluecross:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run Blue Cross tracker
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO_1: ${{ secrets.EMAIL_TO_1 }}
          EMAIL_TO_2: ${{ secrets.EMAIL_TO_2 }}
          DEBUG: "0"
        run: python bluecross-tracker.py

      - name: Commit JSON file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add bluecross_cats.json || echo "No JSON to add"
          git commit -m "Update Blue Cross cats" || echo "No changes"
          git push
